import type { Metadata } from "next";
import { DM_Sans, Montserrat } from "next/font/google";
import "./../globals.css"


// bootstrap

import "bootstrap/dist/css/bootstrap-grid.css";
import { Container } from "react-bootstrap";

// components

import Header from "@/components/Header/Header";


const montserat = Montserrat({ subsets: ["latin"] });
const dmsans = DM_Sans({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserat.className}`}>
        <Container fluid>
          <Header />
        {children}
        </Container>
      </body>
    </html>
  );
}
